# Generated by Django 4.2.4 on 2023-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_name', models.CharField(max_length=50)),
                ('contact_info_email', models.EmailField(max_length=254)),
                ('contact_info_message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_username', models.CharField(max_length=50)),
                ('feedback_userimg', models.ImageField(blank=True, max_length=255, null=True, upload_to='static/pictures')),
                ('feedback_rating', models.IntegerField(default=1)),
                ('feedback_message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frt_pg_title', models.CharField(max_length=20)),
                ('frt_pg_content', models.CharField(max_length=50)),
                ('information_img', models.ImageField(max_length=255, upload_to='static/pictures')),
                ('information_content', models.CharField(max_length=150)),
            ],
        ),
    ]
