# Generated by Django 4.2.4 on 2023-11-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='frt_pg_content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='information_content',
            field=models.CharField(max_length=700),
        ),
    ]
