# Generated by Django 4.2.4 on 2023-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_information', '0002_alter_inspiration_frt_pg_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='information_content',
            field=models.CharField(max_length=1000),
        ),
    ]
