# Generated by Django 4.2.4 on 2023-11-19 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_inst_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_image', models.ImageField(max_length=255, upload_to='static/pictures')),
                ('guide_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=50)),
                ('guide_city', models.CharField(max_length=20)),
                ('guide_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('guide_price', models.IntegerField(default=0)),
                ('guide_phno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_order_id', models.CharField(max_length=50)),
                ('guide_payment_id', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('guide_amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidebk.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gd_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bk_end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guidebk.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityForm_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('bk_start_date', models.DateTimeField()),
                ('bk_end_date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
