# Generated by Django 4.2.4 on 2023-11-19 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookeddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bookeddata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=50)),
                ('depart_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.IntegerField(default=0)),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('Depart_date', models.DateField()),
                ('Return_date', models.DateField(blank=True, null=True)),
                ('Class', models.CharField(default='', max_length=50)),
                ('No_of_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travelbook.flights')),
                ('flight1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to='Travelbook.flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Travelbook.flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travelbook.flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
